{% set name = "orekit_jpype" %}
{% set version = "13.0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a2986ef8391fc7e45ad8dddde3a92f7deebe0bbf4a1231c143b3b10fddd5d54f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - jpype1 =1.6.0
    - numpy
    - openjdk

test:
  imports:
    - orekit_jpype
  requires:
    - python {{ python_min }}
    - pip
    - openjdk
  commands:
    - pip check
    - python -c "import orekit_jpype; orekit_jpype.initVM()"

about:
  home: https://gitlab.orekit.org/orekit/orekit_jpype/-/tree/master
  summary: 'A space dynamics library. This package is a jpype wrapping of the original orekit java code.'
  description: |
    Orekit aims at providing accurate and efficient low level components for
    the development of flight dynamics applications. It is designed to be
    easily used in very different contexts, from quick studies up to critical operations.
    As a library, Orekit provides basic elements (orbits, dates, attitude, frames, ...) and
    various algorithms to handle them (conversions, propagations, pointing, ....).

    The Orekit library is written in java. This package provides a python wrapper to that library.

  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt

  doc_url: https://www.orekit.org/static/apidocs/


extra:
  recipe-maintainers:
    - petrushy
